name: Test non DEV changes
on: [push]

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        poetry-version: [1.6.1]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        env:
          MB_USERNAME: ${{ secrets.MB_USERNAME }}
          MB_PASSWORD: ${{ secrets.MB_PASSWORD }}
        run: poetry run pytest -v
