name: Test non DEV changes
on: [push]

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
        poetry-version: [2.1.1]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        env:
          MB_USERNAME: ${{ secrets.MB_USERNAME }}
          MB_PASSWORD: ${{ secrets.MB_PASSWORD }}
        run: poetry run pytest -v
